; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Nov 06 2020 10:36:48 GMT-0600 (Central Standard Time)
; Wait for set temperatures to be reached
M116 P0

